#spring.application.name=backend

# spring.data.mongodb.uri=mongodb+srv://sanjayjallapuram06_db_user:bg1xUa5YdhLmew9t@cluster0.vn4dcem.mongodb.net/taskmanager?retryWrites=true&w=majority
# jwt.secret=mysupersecretkeymysupersecretkey12345;
# jwt.expiration=86400000;

server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI}

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}